server:
  port: 2001
spring:
  application:
    name: eureka-server
eureka:
  client:
    register-with-eureka: false #禁止自己当做服务注册
    fetch-registry: false       #屏蔽注册信息
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}