// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.lht.pojo.protobuf;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code lht.protbuf.EnumType}
   */
  public enum EnumType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *空消息
     * </pre>
     *
     * <code>NULL_EVENT = 0;</code>
     */
    NULL_EVENT(0),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HEARTBEAT_REQ = 1;</code>
     */
    HEARTBEAT_REQ(1),
    /**
     * <code>HEARTBEAT_RESP = 2;</code>
     */
    HEARTBEAT_RESP(2),
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LOGIN_REQ = 1001;</code>
     */
    LOGIN_REQ(1001),
    /**
     * <code>LOGIN_RESP = 1002;</code>
     */
    LOGIN_RESP(1002),
    /**
     * <pre>
     *创建角色
     * </pre>
     *
     * <code>CREATE_PLAYER_REQ = 1003;</code>
     */
    CREATE_PLAYER_REQ(1003),
    /**
     * <code>CREATE_PLAYER_RESP = 1004;</code>
     */
    CREATE_PLAYER_RESP(1004),
    /**
     * <pre>
     *延迟
     * </pre>
     *
     * <code>PING_REQ = 1007;</code>
     */
    PING_REQ(1007),
    /**
     * <code>PING_RESP = 1008;</code>
     */
    PING_RESP(1008),
    /**
     * <pre>
     *创建账号
     * </pre>
     *
     * <code>CREATE_ACCOUNT_REQ = 1009;</code>
     */
    CREATE_ACCOUNT_REQ(1009),
    /**
     * <code>CREATE_ACCOUNT_RESP = 1010;</code>
     */
    CREATE_ACCOUNT_RESP(1010),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *空消息
     * </pre>
     *
     * <code>NULL_EVENT = 0;</code>
     */
    public static final int NULL_EVENT_VALUE = 0;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>HEARTBEAT_REQ = 1;</code>
     */
    public static final int HEARTBEAT_REQ_VALUE = 1;
    /**
     * <code>HEARTBEAT_RESP = 2;</code>
     */
    public static final int HEARTBEAT_RESP_VALUE = 2;
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LOGIN_REQ = 1001;</code>
     */
    public static final int LOGIN_REQ_VALUE = 1001;
    /**
     * <code>LOGIN_RESP = 1002;</code>
     */
    public static final int LOGIN_RESP_VALUE = 1002;
    /**
     * <pre>
     *创建角色
     * </pre>
     *
     * <code>CREATE_PLAYER_REQ = 1003;</code>
     */
    public static final int CREATE_PLAYER_REQ_VALUE = 1003;
    /**
     * <code>CREATE_PLAYER_RESP = 1004;</code>
     */
    public static final int CREATE_PLAYER_RESP_VALUE = 1004;
    /**
     * <pre>
     *延迟
     * </pre>
     *
     * <code>PING_REQ = 1007;</code>
     */
    public static final int PING_REQ_VALUE = 1007;
    /**
     * <code>PING_RESP = 1008;</code>
     */
    public static final int PING_RESP_VALUE = 1008;
    /**
     * <pre>
     *创建账号
     * </pre>
     *
     * <code>CREATE_ACCOUNT_REQ = 1009;</code>
     */
    public static final int CREATE_ACCOUNT_REQ_VALUE = 1009;
    /**
     * <code>CREATE_ACCOUNT_RESP = 1010;</code>
     */
    public static final int CREATE_ACCOUNT_RESP_VALUE = 1010;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EnumType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EnumType forNumber(int value) {
      switch (value) {
        case 0: return NULL_EVENT;
        case 1: return HEARTBEAT_REQ;
        case 2: return HEARTBEAT_RESP;
        case 1001: return LOGIN_REQ;
        case 1002: return LOGIN_RESP;
        case 1003: return CREATE_PLAYER_REQ;
        case 1004: return CREATE_PLAYER_RESP;
        case 1007: return PING_REQ;
        case 1008: return PING_RESP;
        case 1009: return CREATE_ACCOUNT_REQ;
        case 1010: return CREATE_ACCOUNT_RESP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EnumType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EnumType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EnumType>() {
            public EnumType findValueByNumber(int number) {
              return EnumType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.lht.pojo.protobuf.EventProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final EnumType[] VALUES = values();

    public static EnumType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EnumType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:lht.protbuf.EnumType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022\013lht.protbuf*\345\001\n\010EnumType\022" +
      "\016\n\nNULL_EVENT\020\000\022\021\n\rHEARTBEAT_REQ\020\001\022\022\n\016HE" +
      "ARTBEAT_RESP\020\002\022\016\n\tLOGIN_REQ\020\351\007\022\017\n\nLOGIN_" +
      "RESP\020\352\007\022\026\n\021CREATE_PLAYER_REQ\020\353\007\022\027\n\022CREAT" +
      "E_PLAYER_RESP\020\354\007\022\r\n\010PING_REQ\020\357\007\022\016\n\tPING_" +
      "RESP\020\360\007\022\027\n\022CREATE_ACCOUNT_REQ\020\361\007\022\030\n\023CREA" +
      "TE_ACCOUNT_RESP\020\362\007B#\n\025com.lht.pojo.proto" +
      "bufB\nEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
